# try...catch
为了报错后，不影响后续代码的执行
```js
try{

}catch(e) {

}
如果try里的代码没错，catch里的代码不会执行。
如果try里的代码错了，catch里的代码就会执行。
无论try错不错，外面的代码都不受到影响
```

catch里的方法
    name 错误的种类名字
    message 错误信息
## 错误类型
![](笔记/2020-04-18-13-16-25.png)

